name: kelola-dapur
services:
    kelola-dapur:
        build:
            context: .
            dockerfile: Dockerfile
        image: kelola-dapur:latest
        container_name: kelola-dapur
        restart: unless-stopped
        ports:
            - "8080:8080"
        volumes:
            - ../../storage:/app/storage:cached
            - ../../bootstrap/cache:/app/bootstrap/cache:cached
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - kelola-dapur
networks:
    kelola-dapur:
